(function () {
    "use strict";
    if (window.__MERAYOUR_ADGUARD_ACTIVE__) return;
    window.__MERAYOUR_ADGUARD_ACTIVE__ = true;
    function isBloggerPreview(){const h=(location.hostname||"").toLowerCase();const hr=(location.href||"").toLowerCase();const s=(location.search||"").toLowerCase();const p=(location.pathname||"").toLowerCase();const rf=(document.referrer||"").toLowerCase();if(h==="blogger.com"||h.endsWith(".blogger.com")||h==="draft.blogger.com")return true;if(/(^|[\/_-])layout-preview([\/_-]|$)/i.test(p)||/(^|[\/_-])template-preview([\/_-]|$)/i.test(p))return true;if(s.includes("preview=true")||s.includes("preview=1")||s.includes("blogger.preview"))return true;if(hr.includes("blogger.com")&&(hr.includes("/layout")||hr.includes("/template")||hr.includes("/edit")))return true;if(window!==window.top&&(rf.includes("blogger.com")||rf.includes("blogspot.com")))return true;return false;}
    if(isBloggerPreview())return;
    const CONFIG={logoUrl:"https://blogger.googleusercontent.[STRIPPED 205 bytes]s666",title:"Ad Blocker Detected!",message:"It looks like an ad or content blocker is preventing this page from loading properly. Merayour is a free website supported by readers and advertising. Please allow ads or whitelist Merayour."};
    const WEIGHTS={CRITICAL:70,STRONG:40,MEDIUM:30,WEAK:10};
    let detectionScore=0,legitAdRendered=false,pageLocked=false,lastAdRenderTime=0,missingAdChecks=0;
    const pageLoadStart=performance.now();
    const incidentMap=new Map();
    const evidenceMap={NETWORK:new Set(),DOM_COSMETIC:new Set(),BROWSER_ENGINE:new Set(),RESOURCE:new Set(),REMOVAL:new Set(),SCRIPT_BLOCK:new Set(),DUCKDUCKGO:new Set()};
    const categoryState={NETWORK:false,DOM_COSMETIC:false,BROWSER_ENGINE:false,RESOURCE:false,REMOVAL:false,SCRIPT_BLOCK:false,DUCKDUCKGO:false};
    const INITIAL_GRACE=4000,ADSENSE_LOAD_GRACE=10000,INCIDENT_TTL=4000,INCIDENT_COOLDOWN=1200,LOCAL_WATCH_INTERVAL=1000,NETWORK_WATCH_INTERVAL=6000,AD_MISSING_CONFIRMATIONS=8,REBLOCK_GRACE=10000,CLEAN_CONFIRMATIONS_REQUIRED=2;
    let mainContent=null,originalArticleHTML=null,originalArticleCaptured=false,articleCurrentlyReplaced=false,contentState="NORMAL",cleanStateConfirmations=0,blockStateConfirmations=0,articleRestoreInProgress=false,articleBlockInProgress=false;
    function findMainContent(){if(mainContent&&document.documentElement.contains(mainContent))return mainContent;mainContent=document.querySelector("article,.post-body,.entry-content,main,#main-content");return mainContent;}
    function captureOriginalArticle(){const t=findMainContent();if(!t)return false;if(!originalArticleCaptured){originalArticleHTML=t.innerHTML;originalArticleCaptured=true;}return true;}
    function nowReady(){const e=performance.now()-pageLoadStart;return e>=INITIAL_GRACE&&e>=ADSENSE_LOAD_GRACE;}
    const ua=(navigator.userAgent||""),uaLower=ua.toLowerCase(),vendor=(navigator.vendor||"").toLowerCase();
    const browser={soul:uaLower.includes("soul")||!!window.soul||!!window.__soul_ext__,brave:!!(navigator.brave&&typeof navigator.brave.isBrave==="function"),opera:uaLower.includes("opera")||uaLower.includes("opr/"),chrome:!!window.chrome&&vendor.includes("google"),edge:uaLower.includes("edg/"),firefox:uaLower.includes("firefox"),safari:/safari/.test(uaLower)&&!/chrome|crios|android/.test(uaLower),duckduckgo:/DuckDuckGo/i.test(ua)};
    function isDuckDuckGoBrowser(){return /DuckDuckGo/i.test(ua);}
    function isAggressive(){return browser.brave||browser.opera||browser.firefox||browser.edge||browser.duckduckgo||browser.soul;}
    function getThreshold(){let t=isAggressive()?45:100;if(legitAdRendered)t=320;return t;}
    setInterval(()=>{const n=performance.now();incidentMap.forEach((ts,id)=>{if(n-ts>INCIDENT_TTL)incidentMap.delete(id)});if(detectionScore>0)detectionScore=Math.max(0,detectionScore-5)},1000);
    function clearEvidence(){detectionScore=0;incidentMap.clear();Object.keys(categoryState).forEach(k=>categoryState[k]=false);Object.keys(evidenceMap).forEach(k=>evidenceMap[k].clear());}
    function isAdAttempted(){const ads=document.querySelectorAll("ins.adsbygoogle");if(ads.length===0)return false;return true;}
    function checkRealAdRender(){const ads=document.querySelectorAll("ins.adsbygoogle,.adsbygoogle");let rendered=false;ads.forEach(ad=>{const ifr=ad.querySelector("iframe");if(!ifr)return;const r=ifr.getBoundingClientRect();const st=window.getComputedStyle(ifr);if(r.width>0&&r.height>0&&st.display!=="none"&&st.visibility!=="hidden"&&st.opacity!=="0")rendered=true;});if(rendered){legitAdRendered=true;lastAdRenderTime=performance.now();missingAdChecks=0;clearEvidence();cleanStateConfirmations=0;blockStateConfirmations=0;stopProbing();restoreArticleIfNeeded();unlockPage();}return rendered;}
    function unlockPage(){const o=document.getElementById("ag-lock-overlay");if(o)o.remove();const ls=document.getElementById("ag-lock-style");if(ls)ls.remove();pageLocked=false;if(document.documentElement){document.documentElement.style.removeProperty("overflow");document.documentElement.style.removeProperty("height");}if(document.body){document.body.style.removeProperty("overflow");document.body.style.removeProperty("height");}}
    function createLockOverlay(){if(document.getElementById("ag-lock-overlay"))return;let st=document.getElementById("ag-lock-style");if(!st){st=document.createElement("style");st.id="ag-lock-style";st.textContent=`html,body{overflow:hidden!important} #ag-lock-overlay{position:fixed;inset:0;width:100vw;height:100vh;background:#0d1117;color:#fff;z-index:2147483647;display:flex;align-items:center;justify-content:center;padding:20px;box-sizing:border-box;font-family:system-ui,sans-serif;text-align:center} #ag-lock-overlay.ag-card{width:100%;max-width:400px;padding:32px 24px;background:#161b22;border:1px solid #30363d;border-radius:12px}`;document.head.appendChild(st);}const ov=document.createElement("div");ov.id="ag-lock-overlay";const logo=CONFIG.logoUrl?`<img src="${CONFIG.logoUrl}" alt="Merayour" style="max-width:80px;margin-bottom:16px;border-radius:8px" onerror="this.style.display='none'">`:"";ov.innerHTML=`<div class="ag-card">${logo}<h1>${CONFIG.title}</h1><p>${CONFIG.message}</p></div>`;(document.body||document.documentElement).appendChild(ov);}
    function blockArticleIfNeeded(){if(articleBlockInProgress||articleCurrentlyReplaced)return;const t=findMainContent();if(!t||!captureOriginalArticle())return;articleBlockInProgress=true;try{t.innerHTML=`<div style="padding:30px;text-align:center;color:#fff;">Content Temporarily Unavailable - Please allow ads</div>`;articleCurrentlyReplaced=true;contentState="BLOCKED";}finally{articleBlockInProgress=false;}}
    function restoreArticleIfNeeded(){if(articleRestoreInProgress||!articleCurrentlyReplaced||!originalArticleCaptured)return;const t=findMainContent();if(!t)return;articleRestoreInProgress=true;try{t.innerHTML=originalArticleHTML;articleCurrentlyReplaced=false;contentState="NORMAL";}finally{articleRestoreInProgress=false;}}
    function lockPage(){if(legitAdRendered)return;if(performance.now()-pageLoadStart<ADSENSE_LOAD_GRACE)return;if(!isAdAttempted())return;if(checkRealAdRender())return;if(contentState!=="BLOCKED")blockArticleIfNeeded();createLockOverlay();pageLocked=true;}
    const PROBE_CONFIG={MAX_CYCLES:3,MIN_INTERVAL:8000,START_AFTER:15000,MAX_TOTAL_REQUESTS:6,FAILURE_CONFIRMATIONS:1,TIMEOUT:4000,MAX_LIFETIME:60000};
    const probeState={cycles:0,pixelAttempts:0,pixelSuccesses:0,pixelFailures:0,fetchAttempts:0,fetchSuccesses:0,fetchFailures:0,consecutivePixelFailures:0,consecutiveFetchFailures:0,consecutiveDualFailures:0,lastProbeTime:0,stopped:false,networkSuspicion:0};
    function probeAllowed(){if(probeState.stopped||legitAdRendered||!navigator.onLine||document.visibilityState==="hidden")return false;const e=performance.now()-pageLoadStart;if(e<PROBE_CONFIG.START_AFTER||e>PROBE_CONFIG.MAX_LIFETIME)return false;if(probeState.cycles>=PROBE_CONFIG.MAX_CYCLES)return false;if(probeState.pixelAttempts+probeState.fetchAttempts>=PROBE_CONFIG.MAX_TOTAL_REQUESTS)return false;if(performance.now()-probeState.lastProbeTime<PROBE_CONFIG.MIN_INTERVAL)return false;return true;}
    function updateProbeSuspicion(){let s=0;if(probeState.consecutivePixelFailures>=PROBE_CONFIG.FAILURE_CONFIRMATIONS)s++;if(probeState.consecutiveFetchFailures>=PROBE_CONFIG.FAILURE_CONFIRMATIONS)s++;if(probeState.consecutiveDualFailures>=1)s++;if(probeState.pixelFailures>=1&&probeState.fetchFailures>=1)s++;const suc=probeState.pixelSuccesses+probeState.fetchSuccesses;if(suc>=2)s=Math.max(0,s-1);probeState.networkSuspicion=Math.min(4,s);if(probeState.networkSuspicion>=1){categoryState.NETWORK=true;evidenceMap.NETWORK.add("intelligent_probe");}}
    function runPixelProbe(){return new Promise(res=>{if(!navigator.onLine){res(false);return;}if(probeState.pixelAttempts>=PROBE_CONFIG.MAX_CYCLES){res(false);return;}probeState.pixelAttempts++;const px=new Image();let done=false;const tm=setTimeout(()=>{if(done)return;done=true;probeState.pixelFailures++;probeState.consecutivePixelFailures++;px.src="";res(false);},PROBE_CONFIG.TIMEOUT);px.onload=()=>{if(done)return;done=true;clearTimeout(tm);probeState.pixelSuccesses++;probeState.consecutivePixelFailures=0;res(true);};px.onerror=()=>{if(done)return;done=true;clearTimeout(tm);probeState.pixelFailures++;probeState.consecutivePixelFailures++;res(false);};px.src="https://pagead2.googlesyndication.com/pagead/img/0.gif?ag=ag-"+probeState.pixelAttempts;});}
    async function runFetchProbe(){if(!navigator.onLine||!window.fetch)return false;if(probeState.fetchAttempts>=PROBE_CONFIG.MAX_CYCLES)return false;probeState.fetchAttempts++;const ctrl=typeof AbortController!=="undefined"?new AbortController():null;let tid=null;if(ctrl)tid=setTimeout(()=>{try{ctrl.abort();}catch(_){}},PROBE_CONFIG.TIMEOUT);try{await window.fetch("https://pagead2.googlesyndication.com/pagead/img/0.gif?ag=ag-"+probeState.fetchAttempts,{method:"GET",mode:"no-cors",cache:"no-store",credentials:"omit",signal:ctrl?ctrl.signal:undefined});if(tid)clearTimeout(tid);probeState.fetchSuccesses++;probeState.consecutiveFetchFailures=0;return true;}catch(e){if(tid)clearTimeout(tid);probeState.fetchFailures++;probeState.consecutiveFetchFailures++;return false;}}
    async function runProbeCycle(){if(!probeAllowed())return;probeState.lastProbeTime=performance.now();probeState.cycles++;const [p,f]=await Promise.all([runPixelProbe(),runFetchProbe()]);if(!p&&!f)probeState.consecutiveDualFailures++;else probeState.consecutiveDualFailures=0;updateProbeSuspicion();if(p||f)probeState.networkSuspicion=Math.max(0,probeState.networkSuspicion-1);evaluate();}
    function stopProbing(){probeState.stopped=true;}
    function registerIncident(id,conf,cat,src){if(!cat)return;const n=performance.now();if(incidentMap.has(id)&&n-incidentMap.get(id)<INCIDENT_COOLDOWN)return;incidentMap.set(id,n);const w=WEIGHTS[conf]||WEIGHTS.WEAK;detectionScore+=w;categoryState[cat]=true;if(evidenceMap[cat])evidenceMap[cat].add(src||id);if(evidenceMap.NETWORK.size>0&&evidenceMap.DOM_COSMETIC.size>0)detectionScore+=25;if(evidenceMap.SCRIPT_BLOCK.size>0)detectionScore+=50;if(evidenceMap.DUCKDUCKGO.size>0)detectionScore+=80;setTimeout(evaluate,300);}
    function networkIncident(s){if(!navigator.onLine)return;if(performance.now()-pageLoadStart<ADSENSE_LOAD_GRACE)return;registerIncident("network:"+s,"MEDIUM","NETWORK",s);}
    function createBaits(){if(!document.body)return;["ag-ad-bait-1","ag-ad-bait-2","ag-ad-bait-3"].forEach((id,i)=>{if(document.getElementById(id))return;const b=document.createElement("div");b.id=id;b.dataset.agBait="true";b.className="adsbygoogle";b.style.cssText="display:block!important;visibility:visible!important;width:300px!important;height:250px!important;position:absolute!important;left:0!important;top:0!important;opacity:0.01!important;pointer-events:none!important;z-index:-1!important;";(document.body||document.documentElement).appendChild(b);});}
    function checkCosmetic(){createBaits();if(typeof window.adsbygoogle==="undefined"&&performance.now()-pageLoadStart<ADSENSE_LOAD_GRACE&&!isDuckDuckGoBrowser())return;const targets=document.querySelectorAll("[data-ag-bait],ins.adsbygoogle,.adsbygoogle");targets.forEach(el=>{if(el.dataset.agBait==="true"){const st=getComputedStyle(el);if(st.display==="none"||st.visibility==="hidden"){const h=parseInt(el.dataset.hits||"0",10)+1;el.dataset.hits=String(h);if(h>=2)registerIncident("bait:"+el.id,"STRONG","DOM_COSMETIC",el.id);}else el.dataset.hits="0";return;}if(el.matches("ins.adsbygoogle,.adsbygoogle")){const ifr=el.querySelector("iframe");if(ifr){const r=ifr.getBoundingClientRect();if(r.width>0&&r.height>0)return;}if(el.getAttribute("data-ad-status")==="unfilled")return;if(el.innerHTML.trim()==="")return;const st=getComputedStyle(el);if(st.display==="none"||st.visibility==="hidden"){const h=parseInt(el.dataset.hits||"0",10)+1;el.dataset.hits=String(h);if(h>=2)registerIncident("cosmetic:ad","STRONG","DOM_COSMETIC","hidden_ad");}else el.dataset.hits="0";}});}
    function checkBrowserSignals(){let sc=0;if(browser.soul)sc+=30;if(window.soul||window.__soul_ext__)sc+=40;if(browser.brave)sc+=20;if(browser.opera)sc+=15;if(browser.duckduckgo)sc+=50;if(sc>=30)registerIncident("browser:strong","STRONG","BROWSER_ENGINE","browser_strong");else if(sc>=15)registerIncident("browser:weak","WEAK","BROWSER_ENGINE","browser_weak");}
    function checkScriptBlock(){const ads=document.querySelectorAll("ins.adsbygoogle");if(ads.length===0)return false;if(typeof window.adsbygoogle==="undefined"&&nowReady()){registerIncident("script:blocked","CRITICAL","SCRIPT_BLOCK","adsbygoogle_blocked");registerIncident("resource:script","CRITICAL","RESOURCE","script_blocked");categoryState.SCRIPT_BLOCK=true;categoryState.RESOURCE=true;return true;}return false;}
    function checkDuckDuckGoForce(){if(!isDuckDuckGoBrowser())return false;if(!nowReady())return false;if(legitAdRendered)return false;const ads=document.querySelectorAll("ins.adsbygoogle");if(ads.length===0)return false;if(checkRealAdRender())return false;registerIncident("duckduckgo:force","CRITICAL","DUCKDUCKGO","duckduckgo_browser");categoryState.DUCKDUCKGO=true;detectionScore+=80;return true;}
    function inspectAdState(){const ads=document.querySelectorAll("ins.adsbygoogle,.adsbygoogle");let visible=0,usable=false;ads.forEach(ad=>{const ifr=ad.querySelector("iframe");if(ifr){const r=ifr.getBoundingClientRect();const st=getComputedStyle(ifr);if(r.width>0&&r.height>0&&st.display!=="none"&&st.visibility!=="hidden"&&st.opacity!=="0"){visible++;usable=true;legitAdRendered=true;lastAdRenderTime=performance.now();missingAdChecks=0;}}if(ad.getAttribute("data-ad-status")!=="unfilled")usable=true;});if(visible>0){detectionScore=0;clearEvidence();cleanStateConfirmations=CLEAN_CONFIRMATIONS_REQUIRED;blockStateConfirmations=0;restoreArticleIfNeeded();unlockPage();stopProbing();return;}if(legitAdRendered&&usable){missingAdChecks++;if(missingAdChecks>=AD_MISSING_CONFIRMATIONS){legitAdRendered=false;missingAdChecks=0;clearEvidence();probeState.stopped=false;}}}
    window.addEventListener("error",function(e){const t=e.target;const src=t?.src||t?.href||"";if(/googlesyndication|pagead2|doubleclick|googleadservices/i.test(src)){registerIncident("resource:error:"+src,"STRONG","RESOURCE","resource_error");networkIncident("resource");}},true);
    (function(){const oOpen=XMLHttpRequest.prototype.open,oSend=XMLHttpRequest.prototype.send;XMLHttpRequest.prototype.open=function(m,u){this.__ag_url=typeof u==="string"?u:"";return oOpen.apply(this,arguments);};XMLHttpRequest.prototype.send=function(){this.addEventListener("error",()=>{const u=this.__ag_url||"";if(/pagead2|googlesyndication|doubleclick|googleadservices/i.test(u)){networkIncident("xhr");registerIncident("xhr:error:"+u,"STRONG","RESOURCE","xhr_error");}});return oSend.apply(this,arguments);};})();
    (function(){if(!window.fetch)return;const orig=window.fetch;window.fetch=function(...a){const url=typeof a[0]==="string"?a[0]:a[0]?.url||"";return orig.apply(this,a).then(r=>{if(!r.ok&&r.type!=="opaque"&&/pagead2|googlesyndication|doubleclick|googleadservices/i.test(url))networkIncident("fetch-status");return r;}).catch(err=>{if(/pagead2|googlesyndication|doubleclick|googleadservices/i.test(url)){networkIncident("fetch");registerIncident("fetch:error:"+url,"STRONG","RESOURCE","fetch_error");}throw err;});};})();
    function inspectRemovedNode(n){if(n.nodeType!==1)return;const isAd=n.classList?.contains("adsbygoogle")||n.matches?.("ins.adsbygoogle")||n.querySelector?.(".adsbygoogle, ins.adsbygoogle");if(isAd)registerIncident("removed:"+(n.id||n.className||"ad-node"),"STRONG","REMOVAL","ad_removal");}
    (function(){const obs=new MutationObserver(muts=>{muts.forEach(m=>{m.removedNodes.forEach(inspectRemovedNode);m.addedNodes.forEach(node=>{if(node.nodeType!==1)return;const sus=node.matches?.(".adsbygoogle,ins.adsbygoogle,iframe")||node.querySelector?.(".adsbygoogle,ins.adsbygoogle");if(sus)setTimeout(()=>{checkRealAdRender();inspectAdState();checkCosmetic();evaluate();},150);});});});obs.observe(document.documentElement,{childList:true,subtree:true,attributes:true,attributeFilter:["style","class","hidden","src"]});})();
    function detectCleanState(){if(checkRealAdRender()){cleanStateConfirmations=CLEAN_CONFIRMATIONS_REQUIRED;return true;}const suc=probeState.pixelSuccesses+probeState.fetchSuccesses;if(suc>=2&&probeState.networkSuspicion===0)cleanStateConfirmations++;else cleanStateConfirmations=Math.max(0,cleanStateConfirmations-1);return cleanStateConfirmations>=CLEAN_CONFIRMATIONS_REQUIRED;}
    function detectBlockState(){
        const adSlots=document.querySelectorAll("ins.adsbygoogle,.adsbygoogle");if(adSlots.length===0)return false;if(legitAdRendered)return false;if(!nowReady())return false;
        if(checkDuckDuckGoForce()){blockStateConfirmations++;return true;}
        const isScriptBlocked=checkScriptBlock();
        if(isScriptBlocked){blockStateConfirmations++;return true;}
        const cats=Object.values(categoryState).filter(Boolean).length;
        const hasSignal=evidenceMap.RESOURCE.size>0||evidenceMap.REMOVAL.size>0||evidenceMap.DOM_COSMETIC.size>0||evidenceMap.NETWORK.size>0||evidenceMap.SCRIPT_BLOCK.size>0||evidenceMap.DUCKDUCKGO.size>0;
        if(!hasSignal&&!isAggressive())return false;
        if(detectionScore>=getThreshold()){blockStateConfirmations++;}else{blockStateConfirmations=Math.max(0,blockStateConfirmations-1);}
        return blockStateConfirmations>=1;
    }
    function evaluate(){if(!navigator.onLine)return;if(document.readyState==="loading")return;if(checkRealAdRender())return;if(!nowReady()){checkScriptBlock();checkDuckDuckGoForce();return;}if(articleCurrentlyReplaced||contentState==="BLOCKED"){if(detectCleanState()){cleanStateConfirmations=0;blockStateConfirmations=0;restoreArticleIfNeeded();unlockPage();probeState.stopped=false;detectionScore=0;incidentMap.clear();return;}createLockOverlay();pageLocked=true;return;}if(detectBlockState()){if(checkRealAdRender())return;blockArticleIfNeeded();createLockOverlay();pageLocked=true;return;}}
    function scheduleDelayed(){[7000,12000,15000].forEach(d=>{setTimeout(()=>{if(!navigator.onLine)return;checkRealAdRender();inspectAdState();checkCosmetic();checkBrowserSignals();checkScriptBlock();checkDuckDuckGoForce();evaluate();},d);});}
    function runLocal(){if(!navigator.onLine||checkRealAdRender())return;inspectAdState();if(legitAdRendered&&performance.now()-lastAdRenderTime<REBLOCK_GRACE)return;checkCosmetic();checkBrowserSignals();checkScriptBlock();checkDuckDuckGoForce();evaluate();}
    async function runNet(){if(!navigator.onLine||checkRealAdRender())return;if(legitAdRendered&&performance.now()-lastAdRenderTime<REBLOCK_GRACE)return;await runProbeCycle();evaluate();}
    window.addEventListener("online",()=>{probeState.stopped=false;setTimeout(()=>{checkRealAdRender();inspectAdState();checkCosmetic();evaluate();},1200);});
    document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="visible")setTimeout(()=>{checkRealAdRender();inspectAdState();checkCosmetic();evaluate();},700);});
    function init(){captureOriginalArticle();setTimeout(()=>{runLocal();scheduleDelayed();setInterval(runLocal,LOCAL_WATCH_INTERVAL);setInterval(runNet,NETWORK_WATCH_INTERVAL);},1000);}
    if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init,{once:true});else init();
})();
